### ISSUE TITLE
src/plugins/chat.ts(9,27): error TS2304: Cannot find name 'SearchClient'.

### ISSUE THREAD

**Issue by JasonHaley** [Azure-Samples/azure-openai-rag-workshop#10]
[builder] > backend@1.0.0 build
[builder] > tsc
[builder]
[builder] src/plugins/chat.ts(9,27): error TS2304: Cannot find name 'SearchClient'.
[builder] src/plugins/chat.ts(18,35): error TS2355: A function whose declared type is neither 'undefined', 'void', nor 'any' must return a value.
[builder] src/plugins/chat.ts(31,25): error TS2554: Expected 7 arguments, but got 0.
[builder] Timer: Builder ran for 1m8.8381461s and ended at 2024-01-29T23:47:44Z
[builder] ERROR: failed to build: exit status 1
, stderr: [builder] npm WARN deprecated @bufbuild/connect-node@0.10.1: Connect has moved to its own org @connectrpc and has a stable v1. Run `npx @connectrpc/connect-migrate@latest` to update. See https://github.com/connectrpc/connect-es/releases/tag/v0.13.1 for details.
[builder] npm WARN deprecated @bufbuild/connect@0.10.1: Connect has moved to its own org @connectrpc and has a stable v1. Run `npx @connectrpc/connect-migrate@latest` to update. See https://github.com/connectrpc/connect-es/releases/tag/v0.13.1 for details.
[builder] npm notice
[builder] npm notice New minor version of npm available! 10.2.3 -> 10.4.0
[builder] npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
[builder] npm notice Run `npm install -g npm@10.4.0` to update!
[builder] npm notice
ERROR: failed to build: executing lifecycle: failed with status code: 51

Getting an error message when running azd up in the src/plugins/chat.ts file.

**Comment by sinedied** [comment]
Hello, this is a workshop and if you start from the main branch, you need to complete the code following the steps here: https://aka.ms/ws/openai-rag

If you only want to deploy the final code, you must use the `base` branch: https://github.com/Azure-Samples/azure-openai-rag-workshop/tree/base

**Comment by JasonHaley** [comment]
Ok than you, sorry about the confusion.
