### ISSUE TITLE
Azure CLI commands to deploy the app don't work

### ISSUE THREAD

**Issue by rohitcj** [Azure-Samples/azure-openai-rag-workshop#17]
The following Azure CLI commands listed in the steps don't work, when I try to deploy the app: 
azd auth login
azd up

Could you update the steps to deploy this Web App using the Azure CLI + Azure DevOps extensions?

**Comment by sinedied** [comment]
You need the Azure Developer CLI, which is different from the Azure CLI, please use this link to install it as explained in the prerequisites: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=winget-windows%2Cbrew-mac%2Cscript-linux&pivots=os-windows 

As an alternative, you can use GitHub CodeSpaces or devcontainers to have a fully working environment.

**Comment by sinedied** [comment]
As an addition, keep in mind that it's a workshop, not a ready to deploy sample. You should follow the workshop steps if you want to have a working app.
