### ISSUE TITLE
Insufficient quota 

### ISSUE THREAD

**Issue by naveenkundra** [Azure-Samples/azure-openai-rag-workshop#35]
The steps of provsions are confusing in my opinion and even after going through multiple times and hours of research, couldn't make it work. Lots of Time Lost ! 

InsufficientQuota: This operation require 30 new capacity in quota Tokens Per Minute (thousands) - GPT-35-Turbo, which is bigger than the current available capacity 0. The current quota usage is 1 and the quota limit is 1 for quota Tokens Per Minute (thousands) - GPT-35-Turbo

**Comment by sinedied** [comment]
Hi, is your subscription enabled for OpenAI? You can look at the prerequisites here: https://github.com/Azure-Samples/azure-openai-rag-workshop?tab=readme-ov-file#azure-prerequisites
and fill the form linked here is needed.

This error may happen for many reasons:
- Either your don't have access to Azure OpenAI (you need to fill the form)
- You're trying to deploy in a region where you do not have quota. Some regions have limited capacity, in that case you can try redeploying to another location, for example `eastus2`
